version: "2"

services:
  database:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  myadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    restart: always
    ports:
      - 4440:80
    environment:
      PMA_HOST: database
